blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/NYXwdwMUrq
    about: If you are having issues with usage or have other minor issues, come ask on my Discord server!
